# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  zookeeper:
    container_name: local-zookeeper
    image: confluentinc/cp-zookeeper:6.0.0
    ports:
      - 2181:2181
    hostname: zookeeper
    networks:
      - local_kafka_network
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    container_name: local-kafka
    image: confluentinc/cp-kafka:6.0.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9101:9101
      - 29092:29092
    hostname: kafka
    networks:
      - local_kafka_network
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_JMX_PORT=9101

  kafka-rest:
    container_name: local-kafka-rest
    image: confluentinc/cp-kafka-rest:6.0.0
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 8082:8082
    hostname: kafka-rest
    networks:
      - local_kafka_network
    environment:
      - KAFKA_REST_HOST_NAME=kafka-rest
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_REST_LISTENERS=http://kafka-rest:8082
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081

  kafka-ui:
    container_name: local-kafka-ui
    image: landoop/kafka-topics-ui:latest
    depends_on:
      - kafka-rest
    ports:
      - 8000:8000
    hostname: kafka-ui
    networks:
      - local_kafka_network
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true

  schema-registry:
    container_name: local-schema-registry
    image: confluentinc/cp-schema-registry:6.0.0
    depends_on:
      - kafka
    ports:
      - 8081:8081
    hostname: schema-registry
    networks:
      - local_kafka_network
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:29092
    volumes:
      - ./data/:/data
      - ./schema/:/schema
    command:
      - /bin/bash
      - -c
      - |
        # install httpie
        pip3 install --user httpie
        # install jq
        curl -sL https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o .local/bin/jq && chmod u+x .local/bin/jq
        # start
        /etc/confluent/docker/run

  schema-registry-ui:
    container_name: local-schema-registry-ui
    image: landoop/schema-registry-ui:latest
    depends_on:
      - schema-registry
    ports:
      - 8001:8000
    hostname: schema-registry-ui
    networks:
      - local_kafka_network
    environment:
      - SCHEMAREGISTRY_URL=http://schema-registry:8081
      - PROXY=true

#  # TODO replace kafka-rest+kafka-ui and schema-registry-ui
#  kowl:
#    container_name: local-kowl
#    image: quay.io/cloudhut/kowl:v1.2.1
#    depends_on:
#      - kafka
#      - schema-registry
#    # waits for connections to be available
#    restart: on-failure
#    ports:
#      - 8002:8080
#    hostname: kowl
#    networks:
#      - local_kafka_network
#    entrypoint:
#      - /bin/ash
#      - -c
#      - |
#        mkdir -p /etc/kowl
#        cat > /etc/kowl/config.yaml <<EOF
#          # See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
#          kafka:
#            brokers:
#              - kafka:29092
#            schemaRegistry:
#              enabled: true
#              urls: ["http://schema-registry:8081"]
#          server:
#            listenPort: 8080
#        EOF
#        ./kowl --config.filepath=/etc/kowl/config.yaml

networks:
  local_kafka_network:
